version: "3"
services:
  dev:
    image: lambci/lambda:build-nodejs8.10
    container_name: ikhokha-shopify-proxy-dev
    volumes:
      - .:/code
    working_dir: /code
    command: npm run dev
    ports:
      - 8000:8000
