service:
  name: ${env:APPLICATION_NAME}-${env:ENVIRONMENT}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.ts' 

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10

functions:
  graphql:
    name: ${env:MAIN_FUNCTION_NAME}-${env:ENVIRONMENT}
    handler: handler.appFunction
    events:
      - http:
          cors: true
          method: get
          path: /
      - http:
          cors: true
          method: post
          path: /
  playground:
    name: ${env:PLAYGROUND_FUNCTION_NAME}-${env:ENVIRONMENT}
    handler: playground-handler.appFunction
    events:
      - http:
          cors: true
          method: get
          path: /playground
      - http:
          cors: true
          method: post
          path: /playground

